yr.exception.CancelError
==============================

.. py:exception:: exception yr.exception.CancelError(task_id: str = '')

    任务取消错误。